// <auto-generated />
using System;
using CinemaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaApp.Data.Migrations
{
    [DbContext(typeof(CinemaAppDbContext))]
    partial class CinemaAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CinemaApp.Data.Models.ApplicationUserMovie", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Foreign key to the referenced AspNetUser. Part of the entity composite PK.");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Movie. Part of the entity composite PK.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if ApplicationUserMovie entry is deleted");

                    b.HasKey("ApplicationUserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("ApplicationUserMovies", t =>
                        {
                            t.HasComment("User Watchlist entry in the system.");
                        });
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Cinema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Cinema identifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if cinema is deleted");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Cinema location");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Cinema's manager");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComment("Cinema name");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("Name", "Location")
                        .IsUnique();

                    b.ToTable("Cinemas", t =>
                        {
                            t.HasComment("Cinema in the system");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a1fdfb4-08c9-44a2-a46e-0b3c45ff57b9"),
                            IsDeleted = false,
                            Location = "Sofia, Bulgaria",
                            Name = "Arena Mall Sofia"
                        },
                        new
                        {
                            Id = new Guid("f4c3e429-0e36-47af-99a2-0c7581a7fc67"),
                            IsDeleted = false,
                            Location = "Plovdiv, Bulgaria",
                            Name = "Cinema City Plovdiv"
                        },
                        new
                        {
                            Id = new Guid("5ae6c761-1363-4a23-9965-171c70f935de"),
                            IsDeleted = false,
                            Location = "Varna, Bulgaria",
                            Name = "Eccoplexx Varna"
                        },
                        new
                        {
                            Id = new Guid("be80d2e4-1c91-4e86-9b73-12ef08c9c3d2"),
                            IsDeleted = false,
                            Location = "Sofia, Bulgaria",
                            Name = "IMAX Mall of Sofia"
                        },
                        new
                        {
                            Id = new Guid("33c36253-9b68-4d8a-89ae-f3276f1c3f8a"),
                            IsDeleted = false,
                            Location = "Burgas, Bulgaria",
                            Name = "Cinema City Burgas Plaza"
                        });
                });

            modelBuilder.Entity("CinemaApp.Data.Models.CinemaMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Movie projection identifier");

                    b.Property<int>("AvailableTickets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Count of currently available tickets");

                    b.Property<Guid>("CinemaId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the cinema");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if the movie projection in a cinema is active");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the movie");

                    b.Property<string>("Showtime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("String indicating the showtime of the Movie projection");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("MovieId", "CinemaId", "Showtime")
                        .IsUnique();

                    b.ToTable("CinemasMovies", t =>
                        {
                            t.HasComment("Movie projection in a cinema in the system");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("71a411ec-d23c-4abb-b50c-75571d0a3cff"),
                            AvailableTickets = 120,
                            CinemaId = new Guid("8a1fdfb4-08c9-44a2-a46e-0b3c45ff57b9"),
                            IsDeleted = false,
                            MovieId = new Guid("ae50a5ab-9642-466f-b528-3cc61071bb4c"),
                            Showtime = "18:30"
                        },
                        new
                        {
                            Id = new Guid("30c505d0-9833-4087-9377-43ac8ab34e07"),
                            AvailableTickets = 90,
                            CinemaId = new Guid("f4c3e429-0e36-47af-99a2-0c7581a7fc67"),
                            IsDeleted = false,
                            MovieId = new Guid("68fb84b9-ef2a-402f-b4fc-595006f5c275"),
                            Showtime = "21:00"
                        },
                        new
                        {
                            Id = new Guid("130f6630-5593-4165-8e9e-de718ee1fb72"),
                            AvailableTickets = 70,
                            CinemaId = new Guid("5ae6c761-1363-4a23-9965-171c70f935de"),
                            IsDeleted = false,
                            MovieId = new Guid("16376cc6-b3e0-4bf7-a0e4-9cbd1490522c"),
                            Showtime = "20:15"
                        },
                        new
                        {
                            Id = new Guid("c96549ed-7a19-4e83-856e-976cf306d611"),
                            AvailableTickets = 60,
                            CinemaId = new Guid("33c36253-9b68-4d8a-89ae-f3276f1c3f8a"),
                            IsDeleted = false,
                            MovieId = new Guid("bf9ff8b3-3209-4b18-9f4b-5172c45b73f9"),
                            Showtime = "19:00"
                        },
                        new
                        {
                            Id = new Guid("30864830-db09-412a-a816-6dbaccc1374c"),
                            AvailableTickets = 150,
                            CinemaId = new Guid("be80d2e4-1c91-4e86-9b73-12ef08c9c3d2"),
                            IsDeleted = false,
                            MovieId = new Guid("811a1a9e-61a8-4f6f-acb0-55a252c2b713"),
                            Showtime = "17:45"
                        },
                        new
                        {
                            Id = new Guid("a22c43b7-bd1d-46cd-b419-dba244e533cc"),
                            AvailableTickets = 85,
                            CinemaId = new Guid("f4c3e429-0e36-47af-99a2-0c7581a7fc67"),
                            IsDeleted = false,
                            MovieId = new Guid("e00208b1-cb12-4bd4-8ac1-36ab62f7b4c9"),
                            Showtime = "20:00"
                        },
                        new
                        {
                            Id = new Guid("93f61e0c-6e62-41bb-b4e2-fc770ac48128"),
                            AvailableTickets = 40,
                            CinemaId = new Guid("5ae6c761-1363-4a23-9965-171c70f935de"),
                            IsDeleted = false,
                            MovieId = new Guid("4491b6f5-2a11-4c4c-8c6b-c371f47d2152"),
                            Showtime = "22:30"
                        },
                        new
                        {
                            Id = new Guid("6a7071a9-0c3d-42e5-9514-639c5fb259a3"),
                            AvailableTickets = 100,
                            CinemaId = new Guid("33c36253-9b68-4d8a-89ae-f3276f1c3f8a"),
                            IsDeleted = false,
                            MovieId = new Guid("844d9abd-104d-41ab-b14a-ce059779ad91"),
                            Showtime = "16:00"
                        },
                        new
                        {
                            Id = new Guid("3291c19e-5995-48af-9124-35f855bf8476"),
                            AvailableTickets = 95,
                            CinemaId = new Guid("8a1fdfb4-08c9-44a2-a46e-0b3c45ff57b9"),
                            IsDeleted = false,
                            MovieId = new Guid("02b52bb0-1c2b-49a4-ba66-6d33f81d38d1"),
                            Showtime = "19:45"
                        },
                        new
                        {
                            Id = new Guid("d00af316-049a-4bd5-97c2-c55fcab99783"),
                            AvailableTickets = 80,
                            CinemaId = new Guid("be80d2e4-1c91-4e86-9b73-12ef08c9c3d2"),
                            IsDeleted = false,
                            MovieId = new Guid("777634e2-3bb6-4748-8e91-7a10b70c78ac"),
                            Showtime = "20:30"
                        },
                        new
                        {
                            Id = new Guid("0241c54a-37e7-4c9a-bcfb-43f0a60749e2"),
                            AvailableTickets = 60,
                            CinemaId = new Guid("5ae6c761-1363-4a23-9965-171c70f935de"),
                            IsDeleted = false,
                            MovieId = new Guid("54082f99-023b-4d68-89ac-44c00a0958d0"),
                            Showtime = "17:00"
                        },
                        new
                        {
                            Id = new Guid("0e5c76b7-9e27-4217-a113-5cafd558d00f"),
                            AvailableTickets = 70,
                            CinemaId = new Guid("f4c3e429-0e36-47af-99a2-0c7581a7fc67"),
                            IsDeleted = false,
                            MovieId = new Guid("ab2c3213-48a7-41ea-9393-45c60ef813e6"),
                            Showtime = "18:15"
                        },
                        new
                        {
                            Id = new Guid("ef18d96e-2e5b-4218-b552-e094e98ac178"),
                            AvailableTickets = 50,
                            CinemaId = new Guid("8a1fdfb4-08c9-44a2-a46e-0b3c45ff57b9"),
                            IsDeleted = false,
                            MovieId = new Guid("4491b6f5-2a11-4c4c-8c6b-c371f47d2152"),
                            Showtime = "22:00"
                        },
                        new
                        {
                            Id = new Guid("9d54f01b-b33d-4ed5-8c4c-6874d62b24dd"),
                            AvailableTickets = 110,
                            CinemaId = new Guid("be80d2e4-1c91-4e86-9b73-12ef08c9c3d2"),
                            IsDeleted = false,
                            MovieId = new Guid("e00208b1-cb12-4bd4-8ac1-36ab62f7b4c9"),
                            Showtime = "20:00"
                        });
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Manager identifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Manager's user entity");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Managers", t =>
                        {
                            t.HasComment("Manager in the system");
                        });
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Movie identifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Movie description");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Movie director");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasComment("Movie duration");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Movie genre");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Movie image url from the image store");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows if movie is deleted");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasComment("Movie release date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Movie title");

                    b.HasKey("Id");

                    b.ToTable("Movies", t =>
                        {
                            t.HasComment("Movie in the system");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae50a5ab-9642-466f-b528-3cc61071bb4c"),
                            Description = "Harry Potter and the Goblet of Fire is a 2005 fantasy film directed by Mike Newell from a screenplay by Steve Kloves. It is based on the 2000 novel Harry Potter and the Goblet of Fire by J. K. Rowling.",
                            Director = "Mike Newel",
                            Duration = 157,
                            Genre = "Fantasy",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTI1NDMyMjExOF5BMl5BanBnXkFtZTcwOTc4MjQzMQ@@._V1_.jpg",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(2005, 11, 1),
                            Title = "Harry Potter and the Goblet of Fire"
                        },
                        new
                        {
                            Id = new Guid("777634e2-3bb6-4748-8e91-7a10b70c78ac"),
                            Description = "The Lord of the Rings: The Fellowship of the Ring is a 2001 epic high fantasy adventure film directed by Peter Jackson from a screenplay by Fran Walsh, Philippa Boyens, and Jackson, based on 1954's The Fellowship of the Ring, the first volume of the novel The Lord of the Rings by J. R. R. Tolkien.",
                            Director = "Peter Jackson",
                            Duration = 178,
                            Genre = "Fantasy",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(2001, 5, 1),
                            Title = "Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("68fb84b9-ef2a-402f-b4fc-595006f5c275"),
                            Description = "A thief who enters the dreams of others to steal secrets is given the inverse task: planting an idea into someone's mind.",
                            Director = "Christopher Nolan",
                            Duration = 148,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(2010, 7, 16),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = new Guid("02b52bb0-1c2b-49a4-ba66-6d33f81d38d1"),
                            Description = "Batman faces the Joker, who seeks to create chaos in Gotham through psychological warfare.",
                            Director = "Christopher Nolan",
                            Duration = 152,
                            Genre = "Action",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(2008, 7, 18),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = new Guid("16376cc6-b3e0-4bf7-a0e4-9cbd1490522c"),
                            Description = "A group of explorers travel through a wormhole in space in search of a new habitable planet.",
                            Director = "Christopher Nolan",
                            Duration = 169,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(2014, 11, 7),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = new Guid("811a1a9e-61a8-4f6f-acb0-55a252c2b713"),
                            Description = "A paraplegic Marine is sent to the moon Pandora on a mission but becomes torn between following orders and protecting an alien civilization.",
                            Director = "James Cameron",
                            Duration = 162,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMDEzMmQwZjctZWU2My00MWNlLWE0NjItMDJlYTRlNGJiZjcyXkEyXkFqcGc@._V1_.jpg",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(2009, 12, 18),
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = new Guid("ab2c3213-48a7-41ea-9393-45c60ef813e6"),
                            Description = "A love story unfolds on the doomed voyage of the Titanic.",
                            Director = "James Cameron",
                            Duration = 195,
                            Genre = "Romance",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_.jpg",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(1997, 12, 19),
                            Title = "Titanic"
                        },
                        new
                        {
                            Id = new Guid("844d9abd-104d-41ab-b14a-ce059779ad91"),
                            Description = "A computer hacker learns about the true nature of his reality and his role in the war against its controllers.",
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Duration = 136,
                            Genre = "Sci-Fi",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_.jpg",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(1999, 3, 31),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = new Guid("54082f99-023b-4d68-89ac-44c00a0958d0"),
                            Description = "The story of a man with a kind heart and an incredible life journey.",
                            Director = "Robert Zemeckis",
                            Duration = 142,
                            Genre = "Drama",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(1994, 7, 6),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = new Guid("bf9ff8b3-3209-4b18-9f4b-5172c45b73f9"),
                            Description = "A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family and sent him into slavery.",
                            Director = "Ridley Scott",
                            Duration = 155,
                            Genre = "Action",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(2000, 5, 5),
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = new Guid("e00208b1-cb12-4bd4-8ac1-36ab62f7b4c9"),
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Director = "Frank Darabont",
                            Duration = 142,
                            Genre = "Drama",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(1994, 9, 23),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = new Guid("4491b6f5-2a11-4c4c-8c6b-c371f47d2152"),
                            Description = "The lives of two hitmen, a boxer, and a gangster intertwine in four tales of violence and redemption.",
                            Director = "Quentin Tarantino",
                            Duration = 154,
                            Genre = "Crime",
                            ImageUrl = "https://www.tallengestore.com/cdn/shop/products/PulpFiction-JohnTravoltaAndSamuelLJackson-MovieStill1_d3db6d19-235a-45aa-97b2-ab690665c224.jpg?v=1684129898",
                            IsDeleted = false,
                            ReleaseDate = new DateOnly(1994, 10, 14),
                            Title = "Pulp Fiction"
                        });
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Ticket identifier");

                    b.Property<Guid>("CinemaMovieId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the Movie projection in a Cinema");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 6)")
                        .HasComment("Ticket price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Tickets quantity bought");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Foreign key to the owner of the ticket");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CinemaMovieId", "UserId")
                        .IsUnique();

                    b.ToTable("Tickets", t =>
                        {
                            t.HasComment("Ticket in the system");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CinemaApp.Data.Models.ApplicationUserMovie", b =>
                {
                    b.HasOne("CinemaApp.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("WatchlistMovies")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaApp.Data.Models.Movie", "Movie")
                        .WithMany("UserWatchlists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Cinema", b =>
                {
                    b.HasOne("CinemaApp.Data.Models.Manager", "Manager")
                        .WithMany("ManagedCinemas")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.CinemaMovie", b =>
                {
                    b.HasOne("CinemaApp.Data.Models.Cinema", "Cinema")
                        .WithMany("CinemaMovies")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaApp.Data.Models.Movie", "Movie")
                        .WithMany("MovieProjections")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Manager", b =>
                {
                    b.HasOne("CinemaApp.Data.Models.ApplicationUser", "User")
                        .WithOne("Manager")
                        .HasForeignKey("CinemaApp.Data.Models.Manager", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Ticket", b =>
                {
                    b.HasOne("CinemaApp.Data.Models.CinemaMovie", "CinemaMovieProjection")
                        .WithMany("Tickets")
                        .HasForeignKey("CinemaMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaApp.Data.Models.ApplicationUser", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaMovieProjection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CinemaApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CinemaApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CinemaApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaApp.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Manager");

                    b.Navigation("Tickets");

                    b.Navigation("WatchlistMovies");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Cinema", b =>
                {
                    b.Navigation("CinemaMovies");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.CinemaMovie", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Manager", b =>
                {
                    b.Navigation("ManagedCinemas");
                });

            modelBuilder.Entity("CinemaApp.Data.Models.Movie", b =>
                {
                    b.Navigation("MovieProjections");

                    b.Navigation("UserWatchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
